### PR TITLE
Add pipe as flipped compose

### PR DESCRIPTION
**Pull request by jethrolarson**

### CODE REVIEW

**Comment by jethrolarson** [comment]
If you like this I may add pipeN

**Comment by i-am-tom** [comment]
So, my initial thought was "we don't need this because we have compose and one can do this just as neatly with Function.map", but I think this will be useful for people who've come from Elm/Elixir/whatever who are used to the `|>` operator. I'll update the docs and merge it :)

**Comment by i-am-tom** [comment]
Made the changes, now going to merge - I moved a method and sullied the diff, but I hope you don't mind :) Thanks so much for the PR!

EDIT: and yes, pipeN would be cool! :D

**Comment by jethrolarson** [comment]
I don't mind, thanks for considering it.

I just like pipe because the source reads left to right. It's easy to visualize the data moving through the composition.

**Pull request merged**
